// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATL9pyLZJmRjv4PBBjr-OQb18iqzVg0IU',
    appId: '1:1079595139638:web:7203d88cb3a28ee1604e97',
    messagingSenderId: '1079595139638',
    projectId: 'attms-98d82',
    authDomain: 'attms-98d82.firebaseapp.com',
    storageBucket: 'attms-98d82.appspot.com',
    measurementId: 'G-PR3HMXX99N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz9NID-04K2x1jvlK2nO3sNlLjuxQeFT0',
    appId: '1:1079595139638:android:70e3c5fec58a2bda604e97',
    messagingSenderId: '1079595139638',
    projectId: 'attms-98d82',
    storageBucket: 'attms-98d82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcKpGB072nQqk0JzLct8FaKcUDm4EwiQI',
    appId: '1:1079595139638:ios:4a0262783078ab4e604e97',
    messagingSenderId: '1079595139638',
    projectId: 'attms-98d82',
    storageBucket: 'attms-98d82.appspot.com',
    iosBundleId: 'com.example.attms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcKpGB072nQqk0JzLct8FaKcUDm4EwiQI',
    appId: '1:1079595139638:ios:e9ebe4b79564a497604e97',
    messagingSenderId: '1079595139638',
    projectId: 'attms-98d82',
    storageBucket: 'attms-98d82.appspot.com',
    iosBundleId: 'com.bakhshullah.attms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATL9pyLZJmRjv4PBBjr-OQb18iqzVg0IU',
    appId: '1:1079595139638:web:5deaac85644ebe56604e97',
    messagingSenderId: '1079595139638',
    projectId: 'attms-98d82',
    authDomain: 'attms-98d82.firebaseapp.com',
    storageBucket: 'attms-98d82.appspot.com',
    measurementId: 'G-REKXXWT6CP',
  );
}
