class DefaultData {
  // List allDepartment = [
  //   'BS Balochi',
  //   'Department of English',
  //   'Department of Management Sciences',
  //   'Department of Economics',
  //   'Department of Commerce',
  //   'Department of Computer Science',
  //   'Department of Chemistry',
  //   'Department of Natural and Basic Sciences',
  //   'Department of Law',
  //   'Department of Political Science',
  //   'Department of Education',
  //   'Department of Sociology',
  // ];
  List wholeSubject = [
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 1,
      "Title": "English - I",
      "Code": "SOC-301",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Sociology",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 2,
      "Title": "Pakistan Studies",
      "Code": "SOC-303",
      "Theory": 2,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 3,
      "Title": "Math/Stat - I",
      "Code": "SOC-305",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 4,
      "Title": "Introduction to Political Science",
      "Code": "SOC-307",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 5,
      "Title": "Introduction to Sociology I",
      "Code": "SOC-311",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 6,
      "Title": "Introduction to Mass Communication",
      "Code": "SOC-309",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 7,
      "Title": "English - II",
      "Code": "SOC-302",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 8,
      "Title": "Islamic Studies / Ethics",
      "Code": "SOC-304",
      "Theory": 2,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 9,
      "Title": "Introduction to Computer",
      "Code": "SOC-306",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 10,
      "Title": "Introduction to Psychology",
      "Code": "SOC-308",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 11,
      "Title": "Introduction to Social Work",
      "Code": "SOC-310",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 12,
      "Title": "Introduction To Sociology II",
      "Code": "SOC-312",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 13,
      "Title": "English - III",
      "Code": "SOC-401",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 14,
      "Title": "Introduction to Management",
      "Code": "SOC-403",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 15,
      "Title": "Introduction to Economics",
      "Code": "SOC-405",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 16,
      "Title": "Social Problems of Pakistan",
      "Code": "SOC-407",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 17,
      "Title": "Rural Sociology",
      "Code": "SOC-409",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 18,
      "Title": "Community Development",
      "Code": "SOC-411",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 19,
      "Title": "Balochi",
      "Code": "SOC-402",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 20,
      "Title": "Introduction to Philosophy",
      "Code": "SOC-404",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 21,
      "Title": "Development of Social Thought",
      "Code": "SOC-406",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 22,
      "Title": "Urban Sociology",
      "Code": "SOC-408",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 23,
      "Title": "Gender Studies",
      "Code": "SOC-410",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 24,
      "Title": "Social Psychology",
      "Code": "SOC-412",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 25,
      "Title": "Introduction to Social Research",
      "Code": "SOC-501",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 26,
      "Title": "Organizational Behavior",
      "Code": "SOC-503",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 27,
      "Title": "Sociological Theories",
      "Code": "SOC-505",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 28,
      "Title": "Population Studies",
      "Code": "SOC-507",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 29,
      "Title": "Sociology of Globalization",
      "Code": "SOC-509",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 30,
      "Title": "Quantitative Research Methodology",
      "Code": "SOC-502",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 31,
      "Title": "Project Planning and Management",
      "Code": "SOC-504",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 32,
      "Title": "Social Anthropology",
      "Code": "SOC-506",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 33,
      "Title": "Sociology of Social Change & Development",
      "Code": "SOC-508",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 34,
      "Title": "Social Statistics",
      "Code": "SOC-510",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 35,
      "Title": "Qualitative Research Methodology",
      "Code": "SOC-601",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 36,
      "Title": "Sociology of Health",
      "Code": "SOC-603",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 37,
      "Title": "Sociology of Education",
      "Code": "SOC-605",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 38,
      "Title": "NGO Management",
      "Code": "SOC-607",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 39,
      "Title": "Sociology of Family & Marriage",
      "Code": "SOC-609",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 40,
      "Title": "Political Sociology",
      "Code": "SOC-602",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 41,
      "Title": "Sociology of Religion",
      "Code": "SOC-604",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 42,
      "Title": "Criminology",
      "Code": "SOC-606",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 43,
      "Title": "Sociology of Human Rights",
      "Code": "SOC-608",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 44,
      "Title": "Research Thesis",
      "Code": "SOC-610",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Sociology"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 45,
      "Title": "English I",
      "Code": "ENG-301",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 46,
      "Title": "Islamic Studies",
      "Code": "IST-301",
      "Theory": 2,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 47,
      "Title": "Introduction To Political Science I",
      "Code": "POL-401",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 48,
      "Title": "Mathematics I",
      "Code": "MAT-301",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 49,
      "Title": "Introduction To Psychology",
      "Code": "POL-303",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 50,
      "Title": "Introduction To Philosophy",
      "Code": "POL-306",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 51,
      "Title": "Introduction To Political Science II",
      "Code": "POL-304",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 52,
      "Title": "Introduction To Political Science III",
      "Code": "POL-305",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 53,
      "Title": "English II",
      "Code": "ENG-302",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 54,
      "Title": "Pakistan Studies",
      "Code": "PAK-301",
      "Theory": 2,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 55,
      "Title": "Basic Economics",
      "Code": "ECO-301",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 56,
      "Title": "Introduction To Logic",
      "Code": "POL-302",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 57,
      "Title": "English III",
      "Code": "ENG-401",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 58,
      "Title": "Introduction To Basics In Computer",
      "Code": "COM-401",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 59,
      "Title": "Political System Developed",
      "Code": "POL-401",
      "Theory": 4,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 60,
      "Title": "Everyday Science",
      "Code": "POL-402",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 61,
      "Title": "Introduction To Geopolitics Geographical Politics",
      "Code": "POL-403",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 62,
      "Title": "English II",
      "Code": "ENG-402",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 63,
      "Title": "Political Systems Developing",
      "Code": "POL-404",
      "Theory": 4,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 64,
      "Title": "Geopolitics of Balochistan",
      "Code": "POL-405",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 65,
      "Title": "Introduction To International Relations",
      "Code": "POL-406",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 66,
      "Title": "Public Finance",
      "Code": "POL-407",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 67,
      "Title": "Western Political Philosophy I",
      "Code": "POL-501",
      "Theory": 4,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 68,
      "Title": "Muslim Political Philosophy",
      "Code": "POL-502",
      "Theory": 4,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 69,
      "Title": "Comparative And Developmental Politics I",
      "Code": "POL-503",
      "Theory": 4,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 70,
      "Title": "Diplomacy",
      "Code": "POL-504",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 71,
      "Title": "Introduction To Public Administration",
      "Code": "POL-505",
      "Theory": 4,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 72,
      "Title": "Western Political Philosophy II",
      "Code": "POL-506",
      "Theory": 4,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 73,
      "Title": "Human Rights",
      "Code": "POL-507",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 74,
      "Title": "Comparative And Developmental Politics II",
      "Code": "POL-508",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 75,
      "Title": "International Politics Ninteen Fourtyfive",
      "Code": "POL-509",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 76,
      "Title": "Introduction To Local Governments",
      "Code": "POL-510",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 77,
      "Title": "International Law",
      "Code": "POL-601",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 78,
      "Title": "Foreign Policy of Pakistan",
      "Code": "POL-603",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 79,
      "Title": "Conflict And Conflict Resolution",
      "Code": "POL-604",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 80,
      "Title": "Foreign Policies of Uk Usa And Russia",
      "Code": "POL-605",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 81,
      "Title": "Political Economy of Pakistan",
      "Code": "POL-607",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 82,
      "Title": "International Organization",
      "Code": "POL-608",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 83,
      "Title": "Research Reports And Seminars",
      "Code": "POL-609",
      "Theory": 4,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 84,
      "Title": "Constitutional Development And Politics of Pakistan",
      "Code": "POL-606",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Political Science"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 85,
      "Title": "Study Skills",
      "Code": "GC-101",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 86,
      "Title": "Introduction To Geography",
      "Code": "GC-102",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 87,
      "Title": "Pakistan Studies",
      "Code": "GC-103",
      "Theory": 2,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 88,
      "Title": "English I Reading And Writing Skills",
      "Code": "ELL-101",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 89,
      "Title": "Introduction To Literary Studies",
      "Code": "ELL-102",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 90,
      "Title": "Introduction To Language Studies",
      "Code": "ELL-103",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 91,
      "Title": "Islamic Studies",
      "Code": "GC-104",
      "Theory": 2,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 92,
      "Title": "Elementary Mathematics & Stats",
      "Code": "GC-105",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 93,
      "Title": "Introduction To Philosophy",
      "Code": "GC-106",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 94,
      "Title": "English II Composition Writing",
      "Code": "ELL-104",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 95,
      "Title": "Introduction To Phonetics & Phonology",
      "Code": "ELL-105",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 96,
      "Title": "Literary Forms And Movement",
      "Code": "ELL-106",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 97,
      "Title": "Introduction To Information & Computer Technology (ICT) Skills",
      "Code": "GC-201",
      "Theory": 2,
      "Lab": 1,
      "semester": "semester 03",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 98,
      "Title": "Islamic History & Culture",
      "Code": "GC-202",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 99,
      "Title": "Global Poetry",
      "Code": "GC-203",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 100,
      "Title": "English III Communication And Presentation Skills",
      "Code": "ELL-201",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 101,
      "Title": "Short Fictional Narratives",
      "Code": "ELL-202",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 102,
      "Title": "Introduction To Morphology",
      "Code": "ELL-203",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 103,
      "Title": "Human Rights & Citizenship",
      "Code": "GC-204",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 104,
      "Title": "English IV Academic Reading & Writing",
      "Code": "ELL-204",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 105,
      "Title": "Classical Poetry",
      "Code": "ELL-206",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 106,
      "Title": "Semantics",
      "Code": "ELL-207",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 107,
      "Title": "Rise of the Novel (18th to 19th Century)",
      "Code": "ELL-208",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 108,
      "Title": "Classical and Renaissance Drama",
      "Code": "ELL-205",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 109,
      "Title": "Introduction to International Relations",
      "Code": "GC-301",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 110,
      "Title": "Introduction To Environmental Studies",
      "Code": "GC-302",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 111,
      "Title": "Romantic And Victorian Poetry",
      "Code": "ELL-301",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 112,
      "Title": "Foundation of Literary Theory And Criticism",
      "Code": "ELL-302",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 113,
      "Title": "Sociolinguistics",
      "Code": "ELL-303",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 114,
      "Title": "Popular Fiction",
      "Code": "ELL-304",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 115,
      "Title": "Modern Poetry",
      "Code": "ELL-305",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 116,
      "Title": "Modern Drama",
      "Code": "ELL-306",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 117,
      "Title": "Modern Novel",
      "Code": "ELL-307",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 118,
      "Title": "Grammar And Syntax",
      "Code": "ELL-308",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 119,
      "Title": "Discourse Studies",
      "Code": "ELL-309",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 120,
      "Title": "Creative Nonfiction",
      "Code": "ELL-310",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 121,
      "Title": "Research Methods And Term Paper Writing",
      "Code": "ELL-401",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 122,
      "Title": "Introduction To Applied Linguistics",
      "Code": "ELL-402",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 123,
      "Title": "Introduction To Stylistics",
      "Code": "ELL-403",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 124,
      "Title": "Pakistan Literature In English",
      "Code": "ELL-405",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 125,
      "Title": "Literary Theory and Practice",
      "Code": "ELL-404",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 126,
      "Title": "Postcolonial Literature",
      "Code": "ELL-406",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 127,
      "Title": "Introduction To Translation Studies",
      "Code": "ELL-408",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 128,
      "Title": "World Englishes",
      "Code": "ELL-410",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 129,
      "Title": "American Literature",
      "Code": "ELL-407",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 130,
      "Title": "Introduction to Women’s Writing",
      "Code": "ELL-409",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "Department of English"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 130,
      "Title": "بلوچی وانگ ءُنبیسگ",
      "Code": "IBLC-302",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 131,
      "Title": "(اسلامیات(لازمی",
      "Code": "IBLC-303",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 132,
      "Title": "(01) انگلشں",
      "Code": "IBLC-304",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 133,
      "Title": "بلوچی داستان",
      "Code": "IBLC-305",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 134,
      "Title": "لبزانکی تہر",
      "Code": "IBLC-301",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 01",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 135,
      "Title": "(02) انگلشں",
      "Code": "IBLC-306",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 136,
      "Title": "مطالعہ پاکستان",
      "Code": "IBLC-307",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 137,
      "Title": "بلوچی گیدی شایری",
      "Code": "IBLC-308",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 138,
      "Title": "بلوچی تاریخ ءُ دود ءُ ربیدگ",
      "Code": "IBLC-309",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 139,
      "Title": "نبشتہ رہبندءُبلوچی نبشتہ رہبند",
      "Code": "IBLC-310",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 140,
      "Title": "کُہنیں رِدینک",
      "Code": "IBLC-311",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 02",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 141,
      "Title": "کمپیوٹر 1",
      "Code": "IBLC-312",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 142,
      "Title": "بلوچی گیدی کسّہ",
      "Code": "IBLC-313",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 143,
      "Title": "آزمانک ءِ اِزم",
      "Code": "IBLC-314",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 144,
      "Title": "بلوچی دَرَکسہی لبزانک",
      "Code": "IBLC-315",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 145,
      "Title": "بلوچی کلاسیکل شاعری",
      "Code": "IBLC-316",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 03",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 146,
      "Title": "فلسفہ",
      "Code": "IBLC-317",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 147,
      "Title": "نفسیات",
      "Code": "IBLC-318",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 148,
      "Title": "بلوچی نیم عہدی شاعری",
      "Code": "IBLC-319",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 149,
      "Title": "جام دُرکءِزندءُازم",
      "Code": "IBLC-320",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 150,
      "Title": "کسمانکءُبلوچی کسمانک",
      "Code": "IBLC-321",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 151,
      "Title": "رجانکاری",
      "Code": "IBLC-322",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 04",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 152,
      "Title": "تژن بچکندءُبلوچی لبزانک",
      "Code": "IBLC-323",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 153,
      "Title": "ناول نویسی",
      "Code": "IBLC-324",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 154,
      "Title": "مُلافاضلءِزِندءُاِزم",
      "Code": "IBLC-325",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 155,
      "Title": "زبان زانتی",
      "Code": "IBLC-326",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 156,
      "Title": "بلوچی نوکیں شاعری",
      "Code": "IBLC-327",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 05",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 157,
      "Title": "بلوچی زبان زانتی",
      "Code": "IBLC-328",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 158,
      "Title": "سیدظیورشاہ ھاشمی زِندءُاِزم",
      "Code": "IBLC-329",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 159,
      "Title": "تاکاریءُبلوچی لبزانک",
      "Code": "IBLC-330",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 160,
      "Title": "بلوچی آزمانک",
      "Code": "IBLC-331",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 161,
      "Title": "پولکاری",
      "Code": "IBLC-332",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 06",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 162,
      "Title": "نگدکاری،نکدی لیکہءُمؔیل",
      "Code": "IBLC-333",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 163,
      "Title": "بلوچی ناول",
      "Code": "IBLC-334",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 164,
      "Title": "لبزانکیءُزبان زانتی پولکاری",
      "Code": "IBLC-335",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 165,
      "Title": "رجانکاریءُنلوچی لبزانک",
      "Code": "IBLC-336",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 166,
      "Title": "عطاشادءِزندءُاِزم",
      "Code": "IBLC-337",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 07",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 167,
      "Title": "چاگردی زبان زانتی",
      "Code": "IBLC-338",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 168,
      "Title": "نوکیں دورءِگچین شاعرانی زِندءُاِزم",
      "Code": "IBLC-339",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 169,
      "Title": "بلوچی لبزانکءُنگدکاری",
      "Code": "IBLC-340",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 170,
      "Title": "منیراحمد بادینیءِزندءُاِزم",
      "Code": "IBLC-341",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 171,
      "Title": "تھیسز",
      "Code": "IBLC-342",
      "Theory": 3,
      "Lab": 0,
      "semester": "semester 08",
      "Department": "BS Balochi"
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 170,
      "title": "Islamic Studies/ Ethics",
      "code": "HM-211",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 01',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 171,
      "title": "Applied Physics",
      "code": "PHY-211",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 01',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 172,
      "title": "Applied Physics (Lab)",
      "code": "PHY-211L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 01',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 173,
      "title": "Application of Information & Communication Technologies",
      "code": "ICT-221",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 01',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 174,
      "title": "Application of Information & Communication Technologies (Lab)",
      "code": "ICT-221L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 01',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 175,
      "title": "Discrete Structures",
      "code": "MT-311",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 01',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 176,
      "title": "Functional English",
      "code": "EG-211",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 01',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 177,
      "title": "Ideology and Constitution of Pakistan",
      "code": "HM-212",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 01',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 178,
      "title": "*Basic Mathematics-I",
      "code": "MT-211",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 01',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 179,
      "title": "Programming Fundamentals",
      "code": "CS-221",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 02',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 180,
      "title": "Database Systems",
      "code": "CS-324",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 02',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 181,
      "title": "*Basic Mathematics -II",
      "code": "MT-111",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 02',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 182,
      "title": "Digital Logic Design",
      "code": "CS-327",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 02',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 183,
      "title": "Programming Fundamentals (Lab)",
      "code": "CS-221L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 02',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 184,
      "title": "Database Systems (Lab)",
      "code": "CS-324L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 02',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 185,
      "title": "Calculus & Analytical Geometry",
      "code": "MT-212",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 02',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 186,
      "title": "Digital Logic Design (Lab)",
      "code": "CS-327L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 02',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 187,
      "title": "Expository Writing",
      "code": "EG-232",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 02',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 188,
      "title": "Computer Networks (Lab)",
      "code": "CS-323L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 03',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 189,
      "title": "Probability & Statistics",
      "code": "ST-211",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 03',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 190,
      "title": "Object Oriented Programming",
      "code": "CS-322",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 03',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 191,
      "title": "Object Oriented Programming (Lab)",
      "code": "CS-322L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 03',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 192,
      "title": "Computer Networks",
      "code": "CS-323",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 03',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 193,
      "title": "Linear Algebra",
      "code": "MT-213",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 03',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 194,
      "title": "Software Engineering",
      "code": "CS-312",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 03',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 195,
      "title": "Computer Organization & Assembly Language",
      "code": "CS-425",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 196,
      "title": "Multi-variate Calculus",
      "code": "MT-312",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 197,
      "title": "Data Structures",
      "code": "CS-321",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 198,
      "title": "Web Technologies",
      "code": "CS-364",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 199,
      "title": "Artificial Intelligence",
      "code": "CS-426",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 200,
      "title": "Information Security",
      "code": "CS-313",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 201,
      "title": "Computer Organization & Assembly Language (Lab)",
      "code": "CS-425L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 202,
      "title": "Web Technologies (Lab)",
      "code": "CS-364L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 203,
      "title": "Data Structures (Lab)",
      "code": "CS-321L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 204,
      "title": "Artificial Intelligence (Lab)",
      "code": "CS-426L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 205,
      "title": "Information Security (Lab)",
      "code": "CS-313L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 04',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 206,
      "title": "Technical & Business Writing",
      "code": "EG-312",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 207,
      "title": "Operating Systems",
      "code": "CS-325",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 208,
      "title": "Operating Systems (Lab)",
      "code": "CS-325L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 209,
      "title": "Numerical Analysis",
      "code": "CS-417",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 210,
      "title": "Theory of Automata",
      "code": "CS-315",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 211,
      "title": "Computer Architecture",
      "code": "CS-344",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 212,
      "title": "Computer Architecture (Lab)",
      "code": "CS-344L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 213,
      "title": "Numerical Analysis (Lab)",
      "code": "CS-417L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 214,
      "title": "Cyber Security",
      "code": "CS-345",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 215,
      "title": "Cyber Security (Lab)",
      "code": "CS-345L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 05',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 216,
      "title": "Analysis of Algorithms",
      "code": "CS-343",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 217,
      "title": "Compiler Construction",
      "code": "CS-342",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 218,
      "title": "Compiler Construction (Lab)",
      "code": "CS-342L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 219,
      "title": "Advance Database Management Systems",
      "code": "CS-373",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 220,
      "title": "Advance Database Management Systems (Lab)",
      "code": "CS-373L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 221,
      "title": "HCI & Computer Graphics",
      "code": "CS-346",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 222,
      "title": "HCI & Computer Graphics (Lab)",
      "code": "CS-346L",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 223,
      "title": "Ex: Introduction to Management",
      "code": "MG-225",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 224,
      "title": "Domain Elective – II",
      "code": "-",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 225,
      "title": "Domain Elective – II (Lab)",
      "code": "-",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 06',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 226,
      "title": "Final Year Project – I",
      "code": "CS-471",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 07',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 227,
      "title": "Parallel & Distributed Computing",
      "code": "CS-414",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 07',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 228,
      "title": "Ex: Financial Accounting",
      "code": "MG-428",
      "theory": 3,
      "lab": 0,
      "semester": 'semester 07',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 229,
      "title": "Balochi Language",
      "code": "BL-231",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 07',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 230,
      "title": "Domain Elective – III (Lab)",
      "code": "-",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 07',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 231,
      "title": "Domain Elective – III",
      "code": "-",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 07',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 232,
      "title": "Domain Elective – IV",
      "code": "-",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 07',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 233,
      "title": "Domain Elective – IV (Lab)",
      "code": "-",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 07',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 234,
      "title": "Final Year Project – II",
      "code": "CS-472",
      "theory": 4,
      "lab": 0,
      "semester": 'semester 08',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 235,
      "title": "Entrepreneurship",
      "code": "MG-213",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 08',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 236,
      "title": "Professional Practices",
      "code": "HM-341",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 08',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 237,
      "title": "Civics and Community Engagement",
      "code": "SS-437",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 08',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 238,
      "title": "Domain Elective-VI",
      "code": "-",
      "theory": 2,
      "lab": 0,
      "semester": 'semester 08',
      "Department": "Department of Computer Science",
    },
    {
      'teacherId': 0,
      'name': '',
      "subjectId": 239,
      "title": "Domain Elective-VI (Lab)",
      "code": "-",
      "theory": 0,
      "lab": 1,
      "semester": 'semester 08',
      "Department": "Department of Computer Science",
    }
  ];
  List classesAndDepartments = [
    {
      'Lab': 'yes',
      'classId': 0,
      'Department': 'Department of Management Sciences',
      'className': 'Room 01(lab)',
    },
    {
      'Lab': 'no',
      'classId': 1,
      'Department': 'Department of Management Sciences',
      'className': 'Room 02'
    },
    {
      'Lab': 'no',
      'classId': 2,
      'Department': 'Department of Management Sciences',
      'className': 'Room 04'
    },
    {
      'Lab': 'no',
      'classId': 3,
      'Department': 'Department of Management Sciences',
      'className': 'SLH'
    },
    {
      'Lab': 'yes',
      'classId': 4,
      'Department': 'Department of Computer Science',
      'className': 'Lab 01'
    },
    {
      'Lab': 'yes',
      'classId': 5,
      'Department': 'Department of Computer Science',
      'className': 'Lab 02'
    },
    {
      'Lab': 'yes',
      'classId': 6,
      'Department': 'Department of Computer Science',
      'className': 'Lab 03'
    },
    {
      'Lab': 'no',
      'classId': 7,
      'Department': 'Department of Computer Science',
      'className': 'Lecture Hall'
    },
    {
      'Lab': 'no',
      'classId': 8,
      'Department': 'Department of Computer Science',
      'className': 'Lecture Theature'
    },
    {
      'Lab': 'no',
      'classId': 9,
      'Department': 'BS Balochi',
      'className': 'Room 01'
    },
    {
      'Lab': 'no',
      'classId': 10,
      'Department': 'BS Balochi',
      'className': 'Room 02'
    },
    {
      'Lab': 'no',
      'classId': 11,
      'Department': 'BS Balochi',
      'className': 'Room 04'
    },
    {
      'Lab': 'no',
      'classId': 12,
      'Department': 'BS Balochi',
      'className': 'Lecture Hall'
    },
    {
      'Lab': 'yes',
      'classId': 12,
      'Department': 'Department of English',
      'className': 'Room 03(lab)'
    },
    {
      'Lab': 'no',
      'classId': 14,
      'Department': 'Department of Economics',
      'className': 'Room 07'
    },
    {
      'Lab': 'no',
      'classId': 15,
      'Department': 'Department of Economics',
      'className': 'Room 03'
    },
    {
      'Lab': 'no',
      'classId': 16,
      'Department': 'Department of Commerce',
      'className': 'Room 05'
    },
    {
      'Lab': 'no',
      'classId': 17,
      'Department': 'Department of Commerce',
      'className': 'Room 08'
    },
    {
      'Lab': 'no',
      'classId': 18,
      'Department': 'Department of Commerce',
      'className': 'Lecture Hall'
    },
    {
      'Lab': 'no',
      'classId': 19,
      'Department': 'Department of Chemistry',
      'className': 'Room 01'
    },
    {
      'Lab': 'no',
      'classId': 20,
      'Department': 'Department of Chemistry',
      'className': 'Room 02'
    },
    {
      'Lab': 'no',
      'classId': 21,
      'Department': 'Department of Chemistry',
      'className': 'Room 03'
    },
    {
      'Lab': 'yes',
      'classId': 22,
      'Department': 'Department of Chemistry',
      'className': 'Laboratory'
    },
    {
      'Lab': 'no',
      'classId': 23,
      'Department': 'Department of Chemistry',
      'className': 'Lecture Hall 02'
    },
    {
      'Lab': 'no',
      'classId': 24,
      'Department': 'Department of Education',
      'className': 'Room 03'
    },
    {
      'Lab': 'no',
      'classId': 25,
      'Department': 'Department of Education',
      'className': 'Room 08'
    },
    {
      'Lab': 'no',
      'classId': 26,
      'Department': 'Department of Education',
      'className': 'Room 07'
    },
    {
      'Lab': 'no',
      'classId': 27,
      'Department': 'Department of Education',
      'className': 'Room 06'
    },
    {
      'Lab': 'no',
      'classId': 28,
      'Department': 'Department of Education',
      'className': 'uknown Room 1'
    },
    {
      'Lab': 'no',
      'classId': 29,
      'Department': 'Department of Education',
      'className': 'unknown Room 02'
    },
    {
      'Lab': 'no',
      'classId': 29,
      'Department': 'Department of Botany',
      'className': 'Lecture Hall'
    },
    {
      'Lab': 'no',
      'classId': 30,
      'Department': 'Department of English',
      'className': 'Room 07'
    },
    {
      'Lab': 'no',
      'classId': 31,
      'Department': 'Department of English',
      'className': 'Room 08'
    },
  ];

  List teacherAndDepartment = [
    {
      "teacherId": 0,
      "name": "Dr. Rashid Ali",
      "email": "rashidcs@uot.edu.pk",
      "designation": "Acting Chairperson",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 1,
      "name": "Muhammad Sameer",
      "email": "sameer@uot.edu.pk",
      "designation": "Assistant Professor",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 2,
      "name": "Mazhar Mohsin (On Leave)",
      "email": "mazharmohsin@uot.edu.pk",
      "designation": "Assistant Professor",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 3,
      "name": "Mukhtar Hussain (On Leave)",
      "email": "mukhtar@uot.edu.pk",
      "designation": "Assistant Professor",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 4,
      "name": "Abdul Hakeem",
      "email": "abdul.hakeem@uot.edu.pk",
      "designation": "Lecturer",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 5,
      "name": "Bilal-ur-Rehman",
      "email": "bilalurrehman@uot.edu.pk",
      "designation": "Lecturer",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 6,
      "name": "Balach Khan",
      "email": "balach.khan@uot.edu.pk",
      "designation": "Lecturer",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 7,
      "name": "Pari Naz",
      "email": "parinaz@uot.edu.pk",
      "designation": "Lecturer",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 8,
      "name": "Muhammad Asim",
      "email": "muhammad.asim@uot.edu.pk",
      "designation": "Lecturer",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 9,
      "name": "Mr. Zahoor Ahmed",
      "email": "zahoor.ahmed@uot.edu.pk",
      "designation": "Lecturer",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 10,
      "name": "Mamoon Rasheed",
      "email": "mamoon.rasheed@uot.edu.pk",
      "designation": "Web Developer",
      "Department": "Department of Computer Science",
    },
    {
      "teacherId": 11,
      "name": "Dr. Muhammad Yaseen",
      "email": "muhammad.yaseen@uot.edu.pk",
      "designation": "Chairperson",
      "Department": "BS Sociology",
    },
    {
      "teacherId": 12,
      "name": "Mr. Nadil Shah",
      "email": "nadil.shah@uot.edu.pk",
      "designation": "Lecturer",
      "Department": "BS Sociology"
    },
    {
      "teacherId": 13,
      "name": "Mr. Zahid Ali",
      "email": "zahid.ali@uot.edu.pk",
      "designation": "Lecturer",
      "Department": "BS Sociology"
    },
    {
      "teacherId": 14,
      "name": "Mr. Nooral Barkat",
      "email": "nooral.barkat@uot.edu.pk",
      "designation": "Lecturer",
      "Department": "BS Sociology"
    },
    {
      "teacherId": 24,
      "name": "Changiz Ahmed",
      "email": "changiz.ahmed@uot.edu.pk",
      "designation": "Chairperson - Department of Political Science",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 25,
      "name": "Chaker Hyder",
      "email": "chakar.haider@uot.edu.pk",
      "designation":
          "Principal Staff Officer to Vice Chancellor - Vice Chancellor Secretariat",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 26,
      "name": "Jamil Ahmed",
      "email": "jamil.ahmed@uot.edu.pk",
      "designation": "Lecturer - Department of Political Science",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 27,
      "name": "Muzaffir Hussain",
      "email": "muzaffir.hussain@uot.edu.pk",
      "designation": "Assistant Professor - Department of Political Science",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 28,
      "name": "Nawaz Ahmed",
      "email": "nawazhb@uot.edu.pk",
      "designation": "Lecturer - Department of Political Science",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 29,
      "name": "Shah Hussain",
      "email": "shah@uot.edu.pk",
      "designation": "Lecturer - Department of Political Science",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 30,
      "name": "Bahadin",
      "email": "bahadin@uot.edu.pk",
      "designation": "Lecturer - Department of Political Science",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 31,
      "name": "Mr. Munir Ahmed",
      "email": "munir.anwar@uot.edu.pk",
      "designation": "Lecturer - Department of Political Science",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 32,
      "name": "Dr. Muhammad Salim",
      "email": "dr.muhammadsalim@uot.edu.pk",
      "designation": "Assistant Professor - Department of Political Science",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 33,
      "name": "Farhad Hussain",
      "email": "farhad.hussain@uot.edu.pk",
      "designation": "Lecturer - Department of Political Science",
      "Department": "BS Political Science"
    },
    {
      "teacherId": 45,
      "name": "Prof. Dr. Abdul Saboor",
      "email": "directoriblc@uot.edu.pk",
      "designation": "Director - BS Balochi",
      "Department": "BS Balochi"
    },
    {
      "teacherId": 46,
      "name": "Prof. Dr. Gul Hasan",
      "email": "drgulh@uot.edu.pk",
      "designation":
          "Chairperson - Department of Law, Dean - Faculty of Law, Professor - BS Balochi",
      "Department": "BS Balochi"
    },
    {
      "teacherId": 47,
      "name": "Dr. Ghafoor Shad",
      "email": "ghafoor.shad@uot.edu.pk",
      "designation": "Assistant Professor - BS Balochi",
      "Department": "BS Balochi"
    },
    {
      "teacherId": 48,
      "name": "Tahir Hakeem",
      "email": "tahir.hakeem@uot.edu.pk",
      "designation": "Assistant Professor - BS Balochi",
      "Department": "BS Balochi"
    },
    {
      "teacherId": 49,
      "name": "Aqeel Ahmed",
      "email": "aqeel.ahmed@uot.edu.pk",
      "designation": "Assistant Professor - BS Balochi",
      "Department": "BS Balochi"
    },
    {
      "teacherId": 50,
      "name": "Sadiq Saba",
      "email": "m.sadiq@uot.edu.pk",
      "designation": "Assistant Professor - BS Balochi",
      "Department": "BS Balochi"
    },
    {
      "teacherId": 51,
      "name": "Dr. Rauf Raz",
      "email": "abdul.rauf@uot.edu.pk",
      "designation": "Assistant Professor - BS Balochi",
      "Department": "BS Balochi"
    },
    {
      "teacherId": 52,
      "name": "Tariq Raheem",
      "email": "tariq.raheem@uot.edu.pk",
      "designation": "Assistant Professor - BS Balochi",
      "Department": "BS Balochi"
    },
    {
      "teacherId": 53,
      "name": "Dr. Shah Mir Baloch",
      "email": "shah.mir@uot.edu.pk",
      "designation":
          "Chairperson - Department of English, Assistant Professor - Department of English",
      "Department": "Department of English"
    },
    {
      "teacherId": 54,
      "name": "Durdana Rafiq",
      "email": "durdana.rafiq@uot.edu.pk",
      "designation": "Assistant Professor - Department of English",
      "Department": "Department of English"
    },
    {
      "teacherId": 55,
      "name": "Mr. Adnan Riaz",
      "email": "adnan.riaz@uot.edu.pk",
      "designation": "Assistant Professor - Department of English",
      "Department": "Department of English"
    },
    {
      "teacherId": 56,
      "name": "Hani Abul Hassan",
      "email": "hahasan@uot.edu.pk",
      "designation": "Assistant Professor - Department of English",
      "Department": "Department of English"
    },
    {
      "teacherId": 57,
      "name": "Shaista Hayat",
      "email": "shhayat@uot.edu.pk",
      "designation": "Lecturer - Department of English",
      "Department": "Department of English"
    },
    {
      "teacherId": 58,
      "name": "Adil Khan",
      "email": "akhan@uot.edu.pk",
      "designation": "Lecturer - Department of English",
      "Department": "Department of English"
    },
    {
      "teacherId": 59,
      "name": "Amjid Ali",
      "email": "amjid@uot.edu.pk",
      "designation": "Lecturer - Department of English",
      "Department": "Department of English"
    },
    {
      "teacherId": 60,
      "name": "Mazhar Ali",
      "email": "mazharali@uot.edu.pk",
      "designation": "Lecturer - Department of English",
      "Department": "Department of English"
    },
    {
      'teacherId': 61,
      'name': 'kangaro',
      'subject': 'english',
      'Department': 'visitor'
    },
    {
      'teacherId': 62,
      'name': 'salam',
      'subject': 'islamiat',
      'Department': 'visitor'
    }
  ];
 
}
